build:
    nix-build -E '((import <nixpkgs> {}).callPackage (import ./package.nix) { })'

ui-tests:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs && nix-build . -A nixosTests.qownnotes

ui-tests-logs:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs && nix-store --read-log result

edit-ui-tests:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs && kate ./nixos/tests/qownnotes.nix

edit-app:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs && kate ./pkgs/by-name/qo/qownnotes/package.nix

open-browser:
    xdg-open https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/qo/qownnotes/package.nix
