# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2e693a4b-3032-4da4-a920-b724e1c4468e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-790ee1ef-d6b8-42f0-8605-6715be4f128c".device = "/dev/disk/by-uuid/790ee1ef-d6b8-42f0-8605-6715be4f128c";

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/7E62-DB9C";
    fsType = "vfat";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c6c34295-94b4-4a8f-a1b3-b489874c4872";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."encrypted".device = "/dev/disk/by-uuid/36945148-a697-405c-b907-c2a2a468f05e";

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  #  hardware.video.hidpi.enable = lib.mkDefault true;
}
