build:
    nix-build -E '((import <nixpkgs> {}).callPackage (import ./default.nix) { })' --show-trace

edit-app:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs ; kate ./pkgs/development/tools/jimmy/default.nix
