build:
    nix-build -E '((import <nixpkgs> {}).callPackage (import ./package.nix) { })'

edit-app:
    cd ~/Code/_fork/nixpkgs || cd ~/Code/nixpkgs || cd ~/Code/tools/nixpkgs && kate ./pkgs/by-name/te/television/package.nix

open-browser:
    xdg-open https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/te/television/package.nix
